version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    tty: true

    volumes:
      - .:/app

  black:
    build:
      context: .
      dockerfile: dev/Dockerfile-black

    ports:
      - "45484:45484"

    volumes:
      - .:/app